In [26]:
 
import os
os.getcwd()
import sys
sys.path.append("c:/credit-risk-model")
import pandas as pd
from src.train import split_data
# final_df = pd.read_csv(
#     "../data/processed/final_training_data.csv"
# )

# X_train, X_test, y_train, y_test = (
#     split_data(final_df)
# )

# print(X_train.shape)
# print(X_test.shape)

In [27]:
processed_df = pd.read_csv(
    "../data/processed/processed_data.csv"
)

processed_df.head()

,num__Amount,num__Value,num__transaction_hour,num__transaction_day,num__transaction_month,num__transaction_year,num__total_transaction_amount,num__avg_transaction_amount,num__transaction_count,num__std_transaction_amount,...,cat__ProductCategory_tv,cat__ProductCategory_utility_bill,cat__ChannelId_ChannelId_1,cat__ChannelId_ChannelId_2,cat__ChannelId_ChannelId_3,cat__ChannelId_ChannelId_5,cat__PricingStrategy_0,cat__PricingStrategy_1,cat__PricingStrategy_2,cat__PricingStrategy_4
0,-0.046371,-0.072291,-2.155530,-0.100739,0.848684,-0.994246,0.170118,-0.067623,-0.311831,-0.167524,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,-0.054643,-0.080251,-2.155530,-0.100739,0.848684,-0.994246,0.170118,-0.067623,-0.311831,-0.167524,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,-0.050426,-0.076352,-2.155530,-0.100739,0.848684,-0.994246,0.165122,-0.072568,-0.444993,-0.201719,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,0.107717,0.096648,-1.949214,-0.100739,0.848684,-0.994246,0.175567,-0.008155,-0.404020,-0.008737,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,-0.059704,-0.075183,-1.949214,-0.100739,0.848684,-0.994246,0.175567,-0.008155,-0.404020,-0.008737,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [28]:
target_df = pd.read_csv(
    "../data/processed/target.csv"
)

target_df.head()

        CustomerId  is_high_risk
0     CustomerId_1             1
1    CustomerId_10             1
2  CustomerId_1001             1
3  CustomerId_1002             0
4  CustomerId_1003             0

In [29]:
processed_df.head()

,num__Amount,num__Value,num__transaction_hour,num__transaction_day,num__transaction_month,num__transaction_year,num__total_transaction_amount,num__avg_transaction_amount,num__transaction_count,num__std_transaction_amount,...,cat__ProductCategory_tv,cat__ProductCategory_utility_bill,cat__ChannelId_ChannelId_1,cat__ChannelId_ChannelId_2,cat__ChannelId_ChannelId_3,cat__ChannelId_ChannelId_5,cat__PricingStrategy_0,cat__PricingStrategy_1,cat__PricingStrategy_2,cat__PricingStrategy_4
0,-0.046371,-0.072291,-2.155530,-0.100739,0.848684,-0.994246,0.170118,-0.067623,-0.311831,-0.167524,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,-0.054643,-0.080251,-2.155530,-0.100739,0.848684,-0.994246,0.170118,-0.067623,-0.311831,-0.167524,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,-0.050426,-0.076352,-2.155530,-0.100739,0.848684,-0.994246,0.165122,-0.072568,-0.444993,-0.201719,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,0.107717,0.096648,-1.949214,-0.100739,0.848684,-0.994246,0.175567,-0.008155,-0.404020,-0.008737,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,-0.059704,-0.075183,-1.949214,-0.100739,0.848684,-0.994246,0.175567,-0.008155,-0.404020,-0.008737,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [30]:
processed_df.columns[:10]

Index(['num__Amount', 'num__Value', 'num__transaction_hour',
       'num__transaction_day', 'num__transaction_month',
       'num__transaction_year', 'num__total_transaction_amount',
       'num__avg_transaction_amount', 'num__transaction_count',
       'num__std_transaction_amount'],
      dtype='object')

In [35]:
# final_df = processed_df.merge(
#     target_df,
#     on="CustomerId",
#     how="left"
# )

# final_df.head()

In [36]:
# df_target = df.merge(
#     target_df,
#     on="CustomerId",
#     how="left"
# )

In [38]:

df = pd.read_csv(
    "../data/raw/data.csv"
)
from src.default_estimator import create_transaction_level_target

df_target = create_transaction_level_target(df)

df_target.head()

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult,is_high_risk
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2018-11-15T02:18:49Z,2,0,0
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2018-11-15T02:19:08Z,2,0,0
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,256,ProviderId_6,ProductId_1,airtime,ChannelId_3,500.0,500,2018-11-15T02:44:21Z,2,0,1
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,256,ProviderId_1,ProductId_21,utility_bill,ChannelId_3,20000.0,21800,2018-11-15T03:32:55Z,2,0,0
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-644.0,644,2018-11-15T03:34:21Z,2,0,0

In [39]:
from src.default_estimator import create_transaction_level_target

df_target = create_transaction_level_target(df)

df_target.head()

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult,is_high_risk
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2018-11-15T02:18:49Z,2,0,0
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2018-11-15T02:19:08Z,2,0,0
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,256,ProviderId_6,ProductId_1,airtime,ChannelId_3,500.0,500,2018-11-15T02:44:21Z,2,0,1
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,256,ProviderId_1,ProductId_21,utility_bill,ChannelId_3,20000.0,21800,2018-11-15T03:32:55Z,2,0,0
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-644.0,644,2018-11-15T03:34:21Z,2,0,0

In [40]:
df_target = create_transaction_level_target(df)

print(df_target.shape)
print(df_target["is_high_risk"].value_counts())

(95662, 17)
is_high_risk
0    84653
1    11009
Name: count, dtype: int64

In [41]:
from src.data_processing import process_data

processed_df = process_data(df)

processed_df.shape

(95662, 34)

In [42]:
final_df = processed_df.copy()

final_df["is_high_risk"] = (
    df_target["is_high_risk"].values
)

final_df.head()

,num__Amount,num__Value,num__transaction_hour,num__transaction_day,num__transaction_month,num__transaction_year,num__total_transaction_amount,num__avg_transaction_amount,num__transaction_count,num__std_transaction_amount,...,cat__ProductCategory_utility_bill,cat__ChannelId_ChannelId_1,cat__ChannelId_ChannelId_2,cat__ChannelId_ChannelId_3,cat__ChannelId_ChannelId_5,cat__PricingStrategy_0,cat__PricingStrategy_1,cat__PricingStrategy_2,cat__PricingStrategy_4,is_high_risk
0,-0.046371,-0.072291,-2.155530,-0.100739,0.848684,-0.994246,0.170118,-0.067623,-0.311831,-0.167524,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0
1,-0.054643,-0.080251,-2.155530,-0.100739,0.848684,-0.994246,0.170118,-0.067623,-0.311831,-0.167524,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0
2,-0.050426,-0.076352,-2.155530,-0.100739,0.848684,-0.994246,0.165122,-0.072568,-0.444993,-0.201719,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1
3,0.107717,0.096648,-1.949214,-0.100739,0.848684,-0.994246,0.175567,-0.008155,-0.404020,-0.008737,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0
4,-0.059704,-0.075183,-1.949214,-0.100739,0.848684,-0.994246,0.175567,-0.008155,-0.404020,-0.008737,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0

In [43]:
final_df.shape

(95662, 35)

In [44]:
final_df["is_high_risk"].value_counts()

is_high_risk
0    84653
1    11009
Name: count, dtype: int64

In [45]:
final_df.to_csv(
    "../data/processed/final_training_data.csv",
    index=False
)